package com.example.newinfoapp

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.os.PersistableBundle
import android.util.Log
import androidx.recyclerview.widget.LinearLayoutManager
import by.kirich1409.viewbindingdelegate.viewBinding
import com.example.newinfoapp.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity(R.layout.activity_main) {
    private val binding by viewBinding(ActivityMainBinding::bind)
    private lateinit var adapter: AdapterOfItem

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        initView()
    }

    private fun initView() {
        val repo = mutableListOf<ItemData>(
            ItemData(1, "athlete", "Yao Ming", "Yao Ming (Chinese: 姚明; born September 12, 1980) is a Chinese basketball executive and former professional player.", "There will never be another Yao Ming. We will never again see such a combination of size, strength and agility, never mind the jump shot. We will never again witness one man impact an entire country the way Yao did, single-handedly creating the largest basketball market in the world. And we’ll be hard-pressed to find someone of such fame and status tirelessly dedicating as much of their post-retirement time to humanitarian efforts the way Yao has. The NBA — and the world — has a lot to owe to Yao Ming.", R.drawable.yaoming1, R.drawable.yaoming2),
            ItemData(2, "athlete", "Manny Pacquiao", " Boxing career of Manny Pacquiao.\n" +
                    "In this Philippine name, the middle name or maternal family name is Dapidran and the surname or paternal family name is Pacquiao.", "The Pacman is perhaps the first on this list to check every criteria for inclusion: on top of being super well-known and very influential, he’s also an all-time great in one of the world’s most popular sports. In fact, BoxRec has him ranked as the fourth best pound-for-pound boxer ever.\n" +
                    "With his devastating punching, soft-spoken nature and humble beginnings, the Filipino southpaw has won over millions of fans across the globe over his illustrious career. Now 40 years old, Pacquiao shows no signs of slowing down as he prepares to take on Adrien Broner on Jan. 19.", R.drawable.mannypacquiao, R.drawable.mannypacquiao2),
            ItemData(3, "athlete", "Michelle Kwan", "Michelle Wingshan Kwan (born July 7, 1980) is a retired competitive figure skater and diplomat serving as United States Ambassador to Belize.", "Michelle Kwan perfectly exemplifies the artistry, grace and skill that goes into this under-appreciated sport. The five-time world champion and nine-time national champion is not only the most well-decorated American figure skater of all time, but was also one of the nation’s most popular female athletes, period, during her career.\n" +
                    "Despite never quite securing a gold medal (she won a silver in 1998 and a bronze in 2002), Kwan will go down in history as one of the greatest figure skaters of all time.", R.drawable.michelle_kwan, R.drawable.michelle_kwan2),
            ItemData(4, "athlete", "Liu Xiang", "Liu Xiang at age 20 · Athens 2004 - Xiang Liu ties the 110m hurdles world record · Liu Xiang Wins Gold - Athletics ", "Liu Xiang’s gold medal-winning performance in the 110m hurdles at the 2004 Athen Olympics is still — and perhaps always will be — the single greatest moment in Chinese sporting history. In just a whisker under 13 seconds, he delivered the emphatic message to the entire world that, yes, Asians can do it in track too.\n" +
                    "While the later legs of Liu’s career were plagued by injuries, the former world-record holder remains a national icon. As Chinese track and field undergoes a rejuvenation, the country’s young stars will forever be looking to his lead.", R.drawable.liuxiang, R.drawable.liuxiang2),
            ItemData(5, "athlete", "Li Na", "Li Na (born 26 February 1982) is a Chinese former professional tennis player.", "While Naomi Osaka was nothing short of a revelation in 2018, the Japanese phenom still has a bit of work to do before she officially upends Li Na as Asia’s biggest tennis star.\n" +
                    "The retired 36-year-old from China is a two-time Grand Slam champion, having won the 2011 French Open and the 2014 Australian Open. In 2014, she achieved her career-high ranking of No. 2 in the world.\n" +
                    "In a list full of trailblazers, Li finds herself right at home as the first Chinese tennis player to… well, to have done a lot of things never done before. In fact, she’s such an influential figure in East Asian tennis that a biopic about her career is already in the works.",
                R.drawable.lina, R.drawable.lina2),
            ItemData(6, "athlete", "Ichiro Suzuki", " Ichiro Suzuki (born October 22, 1973, Kasugai, Japan) Japanese baseball player", "Ichiro is a legend. The longtime Mariner made his scintillating MLB debut at the age of 27 after killing it for nine years in Japan’s major leagues, promptly winning both AL Rookie of the Year and AL MVP in his rookie season.\n" +
                    "On top of being a fantastic player, the pioneering outfielder is credited for opening the doors for more of his countrymen to enter the MLB, which currently sees five active Japanese players, including rookie sensation Shohei Ohtani.", R.drawable.ichirosuzuki, R.drawable.ichirosuzuki2),
            ItemData(7, "athlete", "Sun Yang", "Sun Yang is a leading Chinese swimmer who has won Olympic and world titles. He is also a world record-holder.", "Swimming is one of those quintessentially Olympic sports, one that people only really care about every four years. Nevertheless, it’s managed to produce one of the most recognizable names in all of sports: Michael Phelps.\n" +
                    "He’s retired now, though, and we think China’s Sun Yang is right up there to take up that mantle of best swimmer in the world. The 6-foot-7 freestyle specialist is a three-time Olympic gold medallist and nine-time world champion, leaving him trailing only Phelps and American Ryan Lochte for most world titles. He also holds the world record for the 1500m freestyle, and has been described by NBC Sports as “arguably the greatest freestyle swimmer of all time.",R.drawable.sunyang, R.drawable.sunyang2),
            ItemData(8, "athlete", " Cha Bum-kun", "Cha Bum-kun is a South Korean former football manager and player.", "What with their appearance in the World Cup semi-finals in 2002 and their recent gold at the 2018 Asian Games, South Korea stands heads and shoulders above the rest of Asia as the best soccer nation on the continent.\n" +
                    "But before the likes of Manchester United midfielder Park Ji-sung or Tottenham Hotspur star Song Heung-min came to represent the country, there was Cha Bum-kun. A trailblazer for Asians playing in the European leagues, Cha aimed to bring back knowledge and skills from the German Bundesliga to enrich Korean soccer. Nicknamed “Cha Boom” for his incredible striking ability, he remains Korea’s all-time leading goal scorer.", R.drawable.cha, R.drawable.cha2),
            ItemData(9, "athlete", "Sachin Tendulkar", "Sachin Ramesh Tendulkar is an Indian former international cricketer who captained the Indian national team.", "Cricket is thought to have over 2.5 billion fans across the world (the second-most after soccer), thanks mainly to its massive popularity in India and other Commonwealth countries.\n" +
                    "Tendulkar, widely regarded as the greatest batsman of all time, is revered at the level of Pele and Michael Jordan in the cricket world. Having led India to a Cricket World Cup in 2011, a common saying amongst his rabid fanbase goes as follows: “Cricket is my Religion and Tendulkar is my God.” ", R.drawable.sachin, R.drawable.sachin2),
            ItemData(10, "athlete", "Jeremy Lin", "Jeremy Shu-How Lin (born August 23, 1988) is a Taiwanese-American professional basketball player for the New Taipei Kings", "Linsanity caught the world by storm in 2012. The story probably doesn’t need reiterating, but I’ll do it anyway: undrafted, no-name Asian American point guard comes off the end of the bench to become a household name in the span of a week, dropping 38 on Kobe and leading the ailing Knicks to a late-season winning turnaround. It’s the stuff of legends.\n" +
                    "Lin hasn’t been able to maintain the same level of production since — in large part due to injuries — but he’s developed into a solid veteran point guard. It’s his cultural impact, however, that lands him a spot on this list.", R.drawable.jeremy2, R.drawable.jeremy3),
            ItemData(11, "actor", "Henry Golding",  "Henry Ewan Golding (born 5 February 1987) is a Malaysian-born English actor.", "Do you remember “Crazy Rich Asians”? the movie that was packed with laughter and a lot of talented Asian actors and actresses? Henry Golding is a British-Malaysian actor and model who rose to success after his Hollywood debut in this smash film.\n" +
                    "\n" +
                    "When you look at him you can see why he was the perfect fit for the entertainment industry, from his dapper appearance to his interesting charisma everything about him seems to have made him the perfect fit for fame. Before pursuing his career in acting, Golding worked as a travel host and managed to promote the marvels of Southeast Asia to people all over the world. His exposure to different cultures has inspired his acting, and performances and has given him an edge in the industry. ", R.drawable.hengrygolding, R.drawable.hengrygolding2 ),
            ItemData(12, "actor", "Jackie Chan", "Jackie Chan is a Hong Kong actor, director, writer, producer, martial artist", "You can’t think of Jackie Chan without remembering his legendary movies, in those movies he either acted, directed or played his role as a martial artist. Chan is a 1954 Hong Kong native who started out as a stuntman in Bruce Lee movies before becoming a successful starring man on his own.\n" +
                    "\n" +
                    "Though we’ve all seen him in a number of movies, we’re sure you didn’t know that he’s been in over 150 films and that he’s also a UNICEF Goodwill Ambassador as well as a philanthropist.  Jackie Chan is a great icon of the entertainment world with his distinctive flair and unmatched talent.", R.drawable.jackiechan, R.drawable.jackiechan2),
            ItemData(13, "actor", "Michelle Yeoh", "Michelle Yeoh Choo Kheng PSM is a Malaysian actress.", "Once again, Malaysia gave us a treasure known as Michelle Yeoh. Over the years there’s no debate that Michelle has had a big impact on both Eastern and Western movies, she has acted in over 50 movies and TV shows and has a huge loyal fan base.\n" +
                    "\n" +
                    "She’s starred in movies such as  “Police Story 3: Supercop,” a 1992 Hong Kong action classic, which gave her her breakthrough role and catapulted her to international fame. She’s also had roles in famous Hollywood productions like  “Tomorrow Never Dies” and “Crouching Tiger, Hidden Dragon” which clearly showed us her impeccable acting talents and her potential as an action actress. Michelle has also used her influence to advocate for environmental protection and gender equality. ", R.drawable.michelleyeoh, R.drawable.michelleyeoh2),
            ItemData(14, "actor", "Bruce Lee", "Bruce Lee was a Hong Kong-American martial artist and actor. ", "Bruce Lee was born in San Francisco in 194-, he spent his childhood in Hong Kong where he studied Wing Chun, a traditional Chinese martial art. We all know him as an actor, filmmaker and legendary martial artist, but did you know that he moved to the United States to open his own martial arts school? \n" +
                    "Lee took the time to perfect his craft and his discipline eventually turned him into a true icon, his films, including “Enter the Dragon” and “Fist of Fury,” are still loved by fans around the world. Though he died tragically at the age of 32, Bruce Lee’s legacy lives on as an inspiration to countless martial artists and film lovers.", R.drawable.brucelee, R.drawable.bruce_lee2),
            ItemData(15, "actor", "Daniel Dae Kim", "Daniel Dae Kim (born August 4, 1968) is an American actor.", "We know Daniel Dae Kim because of his roles in both television and movies. Daniel was born in South Korea and was brought up in the United States, theatre kickstarted his career in acting before moving on to television in the late 1990s. The popular and personal favourite TV show “Lost” was what really boosted Daniel’s career and shot him to fame.\n" +
                    "\n" +
                    "Kim has starred in many other well-known shows such as  “Hawaii Five-0” and “The Good Doctor.” In addition to his acting skills, Kim is a supporter of increased Asian American presence in Hollywood. Kim has gained popularity in the entertainment industry thanks to his talent and passion for his art, and many people look up to him because of his commitment to social justice.", R.drawable.daniel, R.drawable.daniel2),
            ItemData(16, "actor", "Constance Wu", "Constance Wu (born March 22, 1982) is an American actress.", "Making it in a foreign country and especially America is not as easy as we think it is, however, for those who settle and make it, opportunities start opening up. Wu’s parents who were Taiwanese immigrants were able to settle in Virginia where Wu pursued a career in theatre before breaking into the television and movies industries. \n" +
                    "\n" +
                    "She rose to fame thanks to her depiction of Jessica Huang on the popular TV show “Fresh Off the Boat,” which ran from 2015 to 2020. Wu has also played leading roles in a number of praised movies, such as “Crazy Rich Asians,” which made history as the first entertaining Hollywood production to have an all-Asian cast in 25 years. ", R.drawable.constance_wu, R.drawable.constacewuu3),
            ItemData(17, "actor", "James Hong", "James Hong (Chinese: 吳漢章; born February 22, 1929) is an American actor, producer and director. ", "James Hong is a gifted actor and a Hollywood legend with over 500 credits under his belt. Hong has had a career spanning more than six decades and has starred in many classic movies, such as “Blade Runner,” “Big Trouble in Little China,” and “Kung Fu Panda.” Avatar: The Last Airbender, Mulan, and World of Warcraft are just a few of the animated television shows and video games he has voiced.\n" +
                    "\n" +
                    "Hong is not just an actor but is also a skilled engineer and inventor he has been awarded multiple patents for his ground-breaking works. Despite his impressive record, Hong maintains a humble demeanour and is devoted to his profession, serving as an example to many actors and actresses throughout the years.", R.drawable.jameshong, R.drawable.jameshong2),
            ItemData(18, "actor", "Jimmy O Yang", "JIMMY O. YANG is an actor, stand-up comedian, writer and producer who currently stars & writes on Netflix", "The realm of action cinema has been greatly influenced by the famed martial artist and actor Jet Li. Li, a Chinese citizen who was raised in Beijing, started learning wushu at an early age and finally rose to the position of national champion.\n" +
                    "\n" +
                    "He eventually made the switch to acting, appearing in enduring martial arts films including “Once Once a Time in China,” “Fist of Legend,” and the “Expendables” series. Together with his amazing martial arts prowess, Li is a social activist and philanthropist who supports education and disaster relief initiatives both in China and abroad. Despite recent health issues, Li is still a well-liked and motivational personality in the entertainment world.",R.drawable.jimmy, R.drawable.jimmy2 ),
            ItemData(19, "actor", "Jet Li", "Li Lianjie better known by his stage name Jet Li, is a Chinese-born Singaporean martial artist", "Jet Li is a Chinese citizen who was raised in Beijing and started learning wushu at an early age before rising up to the position of national champion. Jet managed to switch to acting and appeared in martial arts films including “Once Once a Time in China,” “Fist of Legend,” and the “Expendables” series.\n" +
                    "\n" +
                    " Jet is not only a skilled actor but is also a social activist and philanthropist who supports education and disaster relief initiatives both in China and abroad. Despite recent health issues, Li is still a well-liked and motivational personality in the entertainment world.", R.drawable.jetli, R.drawable.jetli2),
            ItemData(20, "actor", "Jessica Henwick", "Jessica Yu-Li Henwick (born 30 August 1992) is a British actress, writer and director.", "Jessica Henwich is a gifted actress who is known for her fascinating roles in both movies and TV shows. Her acting skills have led to a devoted fan base that constantly heaps praise on her acting skills. Henwich outdid herself in the wildly popular HBO series “Game of Thrones,” when she portrayed the tough and talented warrior Nymeria Sand.Since then, she has gone on to feature in more well-known productions, like the Netflix series “Iron Fist,” the blockbuster movie “Star Wars: The Force Awakens,” and the upcoming “Matrix 4.” Jessica Henwick is unquestionably a rising star in Hollywood thanks to her outstanding talent and alluring personality.", R.drawable.jessikahenvik1, R.drawable.jessikahenvik2),
            ItemData(21, "writer", "Dean Koontz", "A new novel and newsletter from the Desk of Dean", "Dean Koontz is an American author and is best known for writing suspense and horror novels that often deal with themes of science fiction, fantasy, and mystery. He has written over 100 novels, many of which have become bestsellers and have been adapted into films and television series. Eight of Koontz's novels have been adapted into films, including Intensity (1997), " +
                    "Phantoms (1998), and Odd Thomas (2013). Koontz’s works have also been adapted into television series, including Mr. Murder (1998) and The Talking (2004).", R.drawable.deankoontz, R.drawable.deankoontz2 ),
            ItemData(22, "writer", "John le Carré ", "avid John Moore Cornwell (19 October 1931 – 12 December 2020), better known by his pen name John le Carré was a British Irish author", "John le Carré was a British author and former intelligence officer. He is best known for writing spy novels that often deal with themes of espionage, betrayal, and political intrigue. Le Carré's works are known for their complex characters, intricate plots, and realistic portrayal of the world of espionage. He wrote over 25 novels, many of which have become bestsellers and have been adapted into films and television series.\n" +
                    "\n" +
                    "So far, 10 of le Carré's novels have been adapted into films and TV series, including The Spy Who Came in from the Cold (1965), Tinker Tailor Soldier Spy (2011), The Constant Gardener (2005), A Most Wanted Man (2014), and The Russia House (1990). Le Carré's works have also been adapted into television series, including The Night Manager (2016), starring Tom Hiddleston and Hugh Laurie, and The Little Drummer Girl (2018).", R.drawable.johnlecarre, R.drawable.johnlecarre2),
            ItemData(23, "writer", "Ian McEwan", "Ian McEwan, our foremost storyteller, has written an ambitious, mesmerising new novel, Lessons.", "Ian McEwan is a British author and screenwriter best known for writing literary fiction that often deals with themes of love, loss, and morality. McEwan has written over 20 novels, many of which have become bestsellers and critically acclaimed.\n" +
                    "\n" +
                    "10 of McEwan's novels have been adapted into films, including Atonement (2007), On Chesil Beach (2017), and The Children Act (2017). These films starred actors such as Keira Knightley, Saoirse Ronan, and Emma Thompson and have been successful at the box office and highly acclaimed by critics. McEwan has also written the screenplay for several of his novels' film adaptations, such as The Good Son (1993) and The Cement Garden (1993).", R.drawable.ian, R.drawable.ian2),
            ItemData(24 , "writer", "Nicholas Sparks ", "Nicholas Charles Sparks (born December 31, 1965) is an American romance novelist, screenwriter, and film producer.", "Nicholas Sparks is an American author and screenwriter best known for writing romance novels that often deal with themes of love, loss, and redemption. Sparks has written over 20 novels, many of which have become bestsellers, with over 100 million copies sold worldwide.Eleven of Sparks' novels have been adapted into films, including The Notebook (2004), A Walk to Remember (2002), and Dear John (2010). These films starred actors such as Ryan Gosling, Rachel McAdams, and Channing Tatum and have been successful at the box office. Sparks has also written the screenplay for several of his novels' film adaptations, including The Last Song (2010) and The Best of Me (2014).",
                R.drawable.nicolas, R.drawable.nicolas2),
            ItemData(25, "writer", "J.K. Rowling", "J.K. Rowling, British author, creator of the popular and critically acclaimed Harry Potter series, about a young sorcerer in training.", "J.K. Rowling is a British author, philanthropist, and screenwriter best known for writing the Harry Potter series, which has become one of the best-selling book series in history, with over 500 million copies sold worldwide. Rowling's works have been translated into over 80 languages and have won numerous awards, including the Hugo Award and the National Book Award. Rowling's transphobia has overshadowed her success in recent years.\n" +
                    "\n" +
                    "By 2023, 11 of Rowling’s novels have been adapted for the screen, and the stage plays. Her Harry Potter series has been adapted into eight films, with the first film, Harry Potter and the Philosopher's Stone, released in 2001. Rowling's works have also been adapted into stage plays, including Harry Potter and the Cursed Child, which premiered in London's West End in 2016. Rowling has also written the screenplay for the film Fantastic Beasts and Where to Find Them (2016) and two more movies in the same franchise released in 2018 and 2022, set in the same universe as the Harry Potter series.", R.drawable.jkrowling, R.drawable.rowling3),
            ItemData(31, "poet", "Homer", "Homer was a Greek poet who is credited as the author of the Iliad and the Odyssey, two epic poems that are foundational works of ancient Greek literature.", "The origins of Homer are so unclear that some scholars describe him as a myth. Many legends about this ancient Greek author circulated; one of the most common is that he was a blind wandering bard from Chios, a city on the Anatolian coast of what is Turkey today.\n" +
                    "\n" +
                    "Even the two major poetry works that are commonly attributed to Homer are a subject of controversy. Some academics think that both texts were written by the same man, a poetry genius, while others consider that the Iliad and the Odyssey are the work and re-writing of many contributors, which eventually were all labelled as belonging to the Homeric tradition. His fame came after his death and he eventually became one of the most beloved of all English poets. His style was characterized by sensual imagery typical of the Romantic movement. Some of his works became so popular that it ranked amongst the most analyzed piece of English literature.", R.drawable.homer_1, R.drawable.homer_2),
            ItemData(32, "poet", "William Shakespeare", "William Shakespeare was an English playwright, poet and actor.", "Maybe the most famous author of all English literature, Shakespeare was a poet, playwright, and actor. He is still regarded today as the world’s most eminent dramatist. While he is mainly known by the public for his numerous theater plays, among which Romeo And Juliet, the most famous romantic tragedy of all time, has been adapted countless times.Still today, Shakespeare rеmains an iconic figurе in thе world of litеraturе. His timеlеss sonnеts and plays, such as \"Hamlеt\" and \"Macbеth\" havе transcеndеd cеnturiеs, captivating audiеncеs with thеir profound insights into thе human condition and influencing poets all over the world. Shakеspеarе's unparallеlеd command of languagе, dеpth of charactеrization and еxploration of univеrsal thеmеs havе solidifiеd his lеgacy as a litеrary giant.",
                R.drawable.shakespeare, R.drawable.william2),
            ItemData(33, "poet", "John Keats", "John Keats (31 October 1795 – 23 February 1821) was an English poet of the second generation of Romantic poets,",
                "John Keats is also amongst the most famous poets of all time, despite or maybe because of his short-lived career. Born in 1795, Keats was part of the second wave of Romantic poets, the artistic movement born in Europe towards the end of the 18th century.\n" +
                        "\n" +
                        "Keats died at the age of 25 years old from tuberculosis. Even though critics did not receive his poems very well during his lifetime, his fame came after his death, and he eventually became one of the most beloved of all English poets. \n" +
                        "\n" +
                        "His style was characterized by a sensual imagery typical of the Romantic movement. Some of his works became so popular that it ranked amongst the most analyzed piece of English literature. Of the most famous piece of poetry he wrote, the “Ode to a Nightingale” is probably the most well-known.", R.drawable.johnkates1, R.drawable.johnkates2),
            ItemData(34, "poet", " Edgar Allan Poe", "Edgar Allan Poe was an American writer, poet, author, editor, and literary critic", "Maybe one of the most famous American poets, Edgar Allan Poe was born in Boston in 1849. Poe was one of the first American writers to try to live solely from his writings. He only succeeded to do so in his late 20’s after joining the Southern Literary Messenger.\n" +
                    "\n" +
                    "Poe had a tumultuous life, abandoned by his father when he was one year old, his mother died a year later. He was adopted by the Allan family with whom he had a rocky relationship. Was it because of his tragic background or because of his Gothic ways? We do not know for sure. Indeed, his work often approached themes such as death, the reanimation of the dead, and mourning.Most of his work is considered to be part of the dark romanticism genre, in opposition to transcendentalism, which Poe openly abhorred. During his career, Poe was one of the first American authors to become popular in Europe, especially in France, where his work was translated by another famous poet, Charles Baudelaire.\n" +
                    "\n" , R.drawable.edgar1, R.drawable.edgar2),
            ItemData(35, "poet","Maya Angelou", "Maya Angelou was an American memoirist, poet, and civil rights activist. ", "Maya Angelou has had an extraordinary life. Born in 1928, in Missouri, she recounted her troubled childhood in her autobiography and international best-seller, I Know Why the Caged Bird Sings, published in 1969. Her book, the first of a seven-volume series, described how she overcame racism and trauma through love and determination.", R.drawable.maya1, R.drawable.maya2
            ),
            ItemData(
                41, "politician", "Abraham Lincoln", "Abraham Lincoln (February 12, 1809 – April 15, 1865)", "Abraham Lincoln (February 12, 1809 – April 15, 1865) was an American lawyer and statesman who served as the 16th president of the United States from 1861 until his assassination in 1865. Lincoln led the nation through the American Civil War and succeeded in preserving the Union, abolishing slavery, bolstering the federal government, and modernizing the U.S. economy.", R.drawable.lincolin, R.drawable.lincolin2
            ),
            ItemData(42, "politician", "Margaret Thatcher", "She was the longest-serving British prime minister of the 20th century and the first woman to hold the position.", "Margaret Hilda Thatcher, Baroness Thatcher, was a British stateswoman and politician who was the Prime Minister of the United Kingdom from 1979 to 1990 and the Leader of the Conservative Party from 1975 to 1990. She was the longest-serving British Prime Minister of the 20th century and was the first ever woman to be Prime Minister, having defeated James Callaghan in the 1979 General Election.",
                R.drawable.margaret, R.drawable.margaret2),
            ItemData(43, "politician", "Franklin D. Roosevelt", "Franklin Delano Roosevelt, commonly known as FDR", "Franklin Delano Roosevelt, commonly known as FDR, was an American statesman and political leader who served as the 32nd President of the United States from 1933 to 1945. A Democrat, he won a record four presidential elections and dominated his party for many years as a central figure in world events during the mid-20th century, leading the United States during a time of worldwide economic depression and total war.", R.drawable.franklin, R.drawable.franklin2),
            ItemData(44, "politician", "Winston Churchill", "Sir Winston Leonard Spencer-Churchill was a British statesman", "Sir Winston Leonard Spencer-Churchill was a British statesman who was the Prime Minister of the United Kingdom from 1940 to 1945 and again from 1951 to 1955. Churchill was also an officer in the British Army, a historian, and a writer.\n" +
                    "Few leaders or people have taken the risks he did, demonstrated true courage, and inspired a world of terrified, war-broken people to carry on fighting against an unspeakably tyrannical enemy.\n" +
                    "\n" +
                    "Stood against the world's most dangerous man.", R.drawable.churchill, R.drawable.churchill2),
            ItemData(45, "politician", "Ronald Reagan", "Ronald Wilson Reagan was an American politician and actor who served as the 40th president of the United States from 1981 to 1989.", "Ronald Wilson Reagan (1911-2004) was an American politician and actor who was 40th President of the United States from 1981 to 1989 . Prior to his presidency, he was the 33rd Governor of California from 1967 to 1975, following a career as a Hollywood actor and union leader until his death in 2004", R.drawable.ronald, R.drawable.ronald2),
            ItemData(46, "politician", "Nelson Mandela", "Nelson Rolihlahla Mandela was a South African anti-apartheid activist", "Nelson Rolihlahla Mandela (18 July 1918 – 5 December 2013) was a South African anti-apartheid activist who served as the first president of South Africa from 1994 to 1999. He was the country's first black head of state and the first elected in a fully representative democratic election. His government... read more\n" +
                    "How is Adolf Hitler, an evil war criminal, higher than Nelson Mandela? Nelson stopped racism in South Africa because he was elected president after he spent many years in prison for speaking out against the white government.", R.drawable.nelson, R.drawable.nelson2),
            ItemData(47, "politician", "Adolf Hitler", "Adolf Hitler (20 April 1889 – 30 April 1945) was an Austrian-born German politician who was the dictator of Nazi Germany from 1933 until his suicide in 1945", "Adolf Hitler (April 20, 1889 - April 30, 1945) was a German politician of Austrian descent who served as the leader of the Nazi Party since 1921, Chancellor of Germany since 1933, and Führer of Nazi Germany since 1934. As dictator of Nazi Germany, he reversed the Treaty of Versailles, initiated World... read more\n" +
                    "I can understand why some people are wondering why he is at the number one spot on this list. Let me explain: The purpose of this list is to find out who is the \"best politician of all time.\" Not the most \"kind-hearted politician\" or the \"most humble politician.\" The criteria of the list are based on who has achieved more accomplishments as a politician. The accomplishments can be righteous or evil in nature. It doesn't matter. Any sort of accomplishments fits the criteria of this list. In this case, Hitler has accomplished more than any other politician on this list. He rose from poverty to become the most powerful person on Earth at a time.\n" +
                    "Sure, most of his accomplishments were evil and cruel in nature. But that doesn't matter for the criteria of this list. He is number one because he has accomplished more than any other politician on this list.", R.drawable.hitler, R.drawable.hitler2),
            ItemData(48, "politician", "Vladimir Lenin", "Vladimir Ilyich Ulyanov (22 April 1870–21 January 1924), better known as Vladimir Lenin", "Vladimir Ilyich Ulyanov (22 April 1870–21 January 1924), better known as Vladimir Lenin, was a Russian revolutionary, politician, and political theorist. He served as the first and founding head of government of Soviet Russia from 1917 to 1924 and of the Soviet Union from 1922 to 1924. Under his administration,... read more\n" +
                    "A great author, a brilliant theorist, a fantastic leader, and an incredible revolutionary - easily and undoubtedly one of the greatest leaders ever. He granted his people free education, housing, food, and healthcare, and laid the groundwork for a democratic nation responding to the needs of all its citizens. I could go on and on about this man, but I believe I have said enough.\n" +
                    "\n" +
                    "The greatest leader ever. He created a new ideology supporting and giving a chance to the poorest people. He took power as his own project. He won the Civil War in Russia, made peace with Germany, and built an absolutely new state, the first in world history to give equal attention to all people. He wrote heaps of works on policy, economics, philosophy.", R.drawable.stalin, R.drawable.stalin2),
            ItemData(49, "politician", "Augustus Caesar", "Gaius Julius Caesar Augustus also known as Octavian", "Even though he never called himself emperor, he is seen as the first and was the most powerful man at the time. His empire would stand for another 1470+ years (if you count the Byzantine empire.)\n" +
                    "\n" +
                    "Augustus Caesar was an astute political operator and skilled administrator. He turned Rome from a city of bricks to one of marble and left an indelible stamp on the Roman and, by extension, the Western world. While not the most proficient military commander and lacking somewhat in empathy and compassion, he had no need for these traits. Instead, he would delegate these tasks to those who were strongest in them, as demonstrated by his lifelong partnership with the general Agrippa. This is the mark of a truly great statesman, knowing which burdens are practical to bear and which are better suited for individuals of a different nature. When it comes to sheer political skill and mastery, Augustus deserves the number 1 spot.",
                R.drawable.august1, R.drawable.augustus2),
            ItemData(50, "politician", "George Washington", "George Washington (February 22, 1732 – December 14, 1799) was an American Founding Father, military officer", "George Washington (February 22, 1732– December 14, 1799) was an American military officer, statesman, and Founding Father who served as the first president of the United States from 1789 to 1797. Appointed by the Continental Congress as commander of the Continental Army, Washington led the Patriot forces to victory in the American Revolutionary War and served as the president of the Constitutional Convention of 1787, which created the Constitution of the United States and the American federal government. Washington has been called the \"Father of the Nation\" for his manifold leadership in the formative days of the country.",
                R.drawable.washington, R.drawable.washington2),
            ItemData(51, "scientist", "Isaac Newton", "Sir Isaac Newton FRS (25 December 1642 – 20 March 1726/27) was an English polymath active as a mathematician, physicist, astronomer, alchemist, theologian", "Isaac Newton was one of the most influential scientists in history, widely known for his theories of gravity and motion. His work also revolutionized mathematics and optics, as well as having a major influence on fields such as chemistry, astronomy, and engineering.\n" +
                    "\n" +
                    "His famous book Philosophiæ Naturalis Principia Mathematica introduced three laws of motion which described how forces interacting between objects affect their behavior when moving. This law is still used today by engineers to design bridges, cars, and aircrafts – among other things. He also developed calculus which became the foundation for much of modern mathematics.\n" +
                    "\n" +
                    "In optics, he discovered that white light is actually composed of all seven colors from the visible spectrum and this discovery led to further advances in understanding color theory and allowed us to develop new technologies like lasers and fiber-optic communications networks. His extensive research into gravity helped him formulate a model for why planets revolve around stars at different speeds based on their distance from it – something no one had been able to do until then – cementing his status as one of the greatest scientists of all time.",
                R.drawable.isaac, R.drawable.isaac2),
            ItemData(52, "scientist", "Charles Darwin", "Charles Robert Darwin FRS FRGS FLS FZS JP was an English naturalist, geologist and biologist", "Charles Darwin is best known for his revolutionary work on the theory of evolution. He proposed that species evolve over generations through a process of natural selection, wherein those individuals who possess advantageous characteristics are more likely to survive and reproduce than their less-favored counterparts.\n" +
                    "\n" +
                    "This groundbreaking insight helped explain how life had changed since its initial emergence and provided an explanation for many of the observations made by scientists in various fields such as geology, zoology, botany, and paleontology. His ideas were initially met with strong resistance from religious groups who believed they challenged accepted notions about creationism but eventually gained acceptance after being rigorously tested against available evidence.\n" +
                    "\n" +
                    "The impact of Darwin’s theories has been immense: it helped establish evolutionary biology as a legitimate field within science, which has led to further discoveries into how organisms change over time in response to environmental pressures.\n" +
                    "\n" +
                    "Today, it continues to influence fields like genetics, anthropology, and medicine, making Charles Darwin one of the top 10 scientists in the world.", R.drawable.charles, R.drawable.charles2),
            ItemData(53, "scientist", " Galileo Galilei", "He was one of the earliest Renaissance developers of the thermoscope ", "Galileo Galilei was one of the most influential scientists of all time, with his revolutionary discoveries in astronomy, physics, and mathematics. He developed the first telescope and used it to observe objects in space that were previously invisible to the naked eye. With this instrument he discovered four moons orbiting Jupiter as well as sunspots on its surface – which showed that Earth is not at the center of our solar system – a concept previously thought to be true by many scholars.\n" +
                    "\n" +
                    "He also developed powerful mathematical methods for understanding physical phenomena such as inertia, acceleration, and motion, laying down an important foundation for Newton’s three laws of motion.\n" +
                    "\n" +
                    "His work helped revolutionize fields such as optics, mechanics, and astronomy while inspiring generations of future scientists with his inventive theories about how our universe works. Today, we owe much of what we know about movement in space to Galileo’s pioneering research into these areas.", R.drawable.galileo, R.drawable.galileo2),
            ItemData(54, "scientist", "Albert Einstein", "Albert Einstein was a German-born theoretical physicist who is widely held to be one of the greatest and most influential scientists of all time.", "Albert Einstein was a German-born physicist who achieved lasting fame for his ground-breaking theories of relativity. His famous equation E=mc2 showed the relationship between energy and mass, which helped scientists understand how nuclear energy is released from atoms and opened up new possibilities in terms of harnessing this powerful source of energy.\n" +
                    "\n" +
                    "He also proposed the theory of general relativity, which helped explain the effects of gravity and how it affects objects in space. This led to a better understanding of how our universe works, with Einstein’s work inspiring countless other scientists in fields such as astrophysics and quantum mechanics. To this day his theories are still being explored and tested, showing just how revolutionary and far-reaching his ideas were as one of the greatest physicist of all time.", R.drawable.albert1, R.drawable.albert2),
            ItemData(55, "scientist", "Nikola Tesla", "Nikola Tesla was a pioneering Serbian American inventor, physicist, and engineer", "Nikola Tesla was a pioneering Serbian American inventor, physicist, and engineer who made numerous contributions to the fields of electrical engineering and physics. He is best known for his development of alternating current (AC) electricity and is credited with inventing the first practical AC motor.\n" +
                    "\n" +
                    "Born in 1856 to Serbian parents, Tesla studied at the Technical University of Graz in Austria and later moved to the United States where he worked for companies such as Edison Machine Works and Westinghouse Electric & Manufacturing Company.\n" +
                    "\n" +
                    "He pioneered techniques like wireless transmission, radio control technology, and fluorescent lighting, which remain important features of modern electricity infrastructure today. His inventions were revolutionary for their time and paved the way for the development of modern electronics and communication. He is also remembered as among the greatest scientists of all time for his innovative ideas such as a worldwide wireless energy system, which he believed would make electricity available to everyone for free.",
                R.drawable.tesla, R.drawable.tesla2
                ),
            ItemData(56, "scientist", "Marie Curie", "Marie Curie is one of the most iconic figures in science, having been the first woman to win a Nobel Prize", "Marie Curie is one of the most iconic figures in science, having been the first woman to win a Nobel Prize and the only person ever to have won two Nobel Prizes in different fields. She was born into a family of teachers in Poland and went on to study physics and mathematics at universities in Paris, France. Her work focused on the discovery and study of radioactive elements such as uranium, radium, and polonium.\n" +
                    "\n" +
                    "This work led to her development of the theory that radiation was caused by atoms releasing energy, which laid the foundations for modern nuclear physics. She also discovered two new elements – radiothorium and radium – for which she won a Nobel Prize in Physics.\n" +
                    "\n" +
                    "She won a second Nobel Prize for her work in chemistry, making her the first woman ever to win two Nobel Prizes and the only person to win two Nobel Prizes in different fields, thereby cementing her legacy among the top 10 scientists in the world.",
                   R.drawable.marie, R.drawable.marie2
                ),
            ItemData(57, "scientist", "Richard Feynman", "Richard Feynman was an American theoretical physicist and Nobel Laureate", "Richard Feynman was an American theoretical physicist and Nobel Laureate,  who made significant contributions to the field of quantum mechanics. He is best known for his work on path integrals, he is a one of the famous scientists which gave a new approach to understanding quantum mechanics by using mathematical diagrams called Feynman diagrams. He also developed a method of quantum electrodynamics (QED), which is an important field of physics that describes the behavior of light and matter.\n" +
                    "\n" +
                    "His work in QED helped to explain the interactions between particles at a subatomic level, leading to his Nobel Prize in 1965. He also wrote popular books on science, such as “Six Easy Pieces” which explained the fundamentals of quantum mechanics for a general audience.\n" +
                    "\n" +
                    "Feynman was a great communicator and popularized science through lectures, books, television appearances and public speaking. He also popularized the concept of “thinking like a physicist,” which is an approach to problem solving that emphasizes the need for creative thought and experimentation.\n" +
                    "\n" +
                    "Feynman’s work revolutionized the field of quantum mechanics and laid the foundations of modern physics. His innovative discoveries are still studied in classrooms around the world and his work has had a lasting impact on our understanding of the universe.",
                R.drawable.richard, R.drawable.richard2
                ),
            ItemData(58, "scientist", "Johannes Kepler", "Johannes Kepler was a German mathematician and astronomer whose laws of planetary motion were revolutionary for their time.", "Johannes Kepler was a German mathematician and astronomer whose laws of planetary motion were revolutionary for their time. His first law, which states that planets move in elliptical orbits around the Sun, contradicted then-current beliefs about astronomy. He also created his second law of planetary motion, which states that a planet’s speed changes as it moves closer or further from the Sun.\n" +
                    "\n" +
                    "Kepler’s laws of planetary motion revolutionized astronomy and paved the way for Isaac Newton’s law of universal gravitation. He also made important contributions to mathematics, optics, and astrology. He is remembered today as one of the greatest scientists of all time who helped shape our understanding of the universe and beyond.",
                R.drawable.johannes, R.drawable.johannes2
            )


        )
        val data = DataManager.addList(repo)

        var type = "athlete"
        var listItem = DataManager.getItemListByType(type)

        adapter = AdapterOfItem()
        adapter.submitList(listItem)

        binding.container.adapter = adapter
        binding.container.layoutManager = LinearLayoutManager(this)

        binding.athlete.setOnClickListener {
            Log.d("TTT", "athlete")
            type = "athlete"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }

        binding.actors.setOnClickListener {
            Log.d("TTT", "actors")
            type = "actor"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }
        binding.writers.setOnClickListener {
            Log.d("TTT", "writers")

            type = "writer"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }
        binding.poets.setOnClickListener {
            Log.d("TTT", "poets")

            type = "poet"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }
        binding.politicians.setOnClickListener {
            Log.d("TTT", "politicians")

            type = "politician"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }
        binding.scientist.setOnClickListener {
            Log.d("TTT", "scientist")

            type = "scientist"
            listItem = DataManager.getItemListByType(type)
            adapter.submitList(listItem)
        }

        adapter.setOnClickItem { data ->
            val bundle = Bundle()
            bundle.putInt("id", data.id)

            val fragment = ItemInfoScreen()
            fragment.arguments = bundle

            supportFragmentManager.beginTransaction()
                .add(R.id.main_container, fragment)
                .addToBackStack(null)
                .commit()
        }
    }
}
